In [2]:
import json
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from tqdm import tqdm
import pickle

In [1]:
ids = []
labels = []
corpus = []
unk_tokens = []


for datapoint in data:
    ids.append(datapoint['id'])
    labels.append(datapoint['cuisine'])
    temp = []
    for ing in datapoint['ingredients']:
        unk_tokens.append(ing)





NameError: name 'data' is not defined

39774

In [63]:
A = np.asmatrix(oh_matrix).T
A.shape

(6714, 39774)

In [85]:
from collections import Counter
ic = Counter(unk_tokens)
len(ic)
ic

Counter({'romaine lettuce': 270,
         'black olives': 229,
         'grape tomatoes': 228,
         'garlic': 7380,
         'pepper': 4438,
         'purple onion': 1896,
         'seasoning': 137,
         'garbanzo beans': 148,
         'feta cheese crumbles': 358,
         'plain flour': 154,
         'ground pepper': 385,
         'salt': 18049,
         'tomatoes': 3058,
         'ground black pepper': 4785,
         'thyme': 361,
         'eggs': 3388,
         'green tomatoes': 108,
         'yellow corn meal': 341,
         'milk': 2263,
         'vegetable oil': 4385,
         'mayonaise': 781,
         'cooking oil': 483,
         'green chilies': 768,
         'grilled chicken breasts': 5,
         'garlic powder': 1442,
         'yellow onion': 1184,
         'soy sauce': 3296,
         'butter': 4848,
         'chicken livers': 65,
         'water': 7457,
         'wheat': 26,
         'black pepper': 2627,
         'shallots': 1477,
         'cornflour': 103,
       

In [90]:
threshold = 3
filtered = {k:v for k,v in dict(ic).items() if v >= threshold}


4159

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
# create the transform
vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(corpus)
# summarize
print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(corpus)
# summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())

{'romainelettuce': 5174, 'blackolives': 511, 'grapetomatoes': 2775, 'garlic': 2620, 'pepper': 4478, 'purpleonion': 4837, 'seasoning': 5375, 'garbanzobeans': 2614, 'fetacheesecrumbles': 2232, 'plainflour': 4626, 'groundpepper': 2912, 'salt': 5265, 'tomatoes': 6183, 'groundblackpepper': 2878, 'thyme': 6131, 'eggs': 2055, 'greentomatoes': 2861, 'yellowcornmeal': 6731, 'milk': 3967, 'vegetableoil': 6432, 'mayonaise': 3866, 'cookingoil': 1522, 'greenchilies': 2832, 'grilledchickenbreasts': 2867, 'garlicpowder': 2638, 'yellowonion': 6743, 'soysauce': 5737, 'butter': 773, 'chickenlivers': 1098, 'water': 6500, 'wheat': 6516, 'blackpepper': 513, 'shallots': 5420, 'cornflour': 1545, 'cayennepepper': 976, 'onions': 4250, 'garlicpaste': 2635, 'lemonjuice': 3554, 'chilipowder': 1153, 'passata': 4393, 'oil': 4216, 'groundcumin': 2894, 'bonelesschickenskinlessthigh': 586, 'garammasala': 2612, 'doublecream': 1879, 'naturalyogurt': 4123, 'bayleaf': 355, 'sugar': 5905, 'freshgingerroot': 2439, 'groundci

(39774, 6782)
<class 'scipy.sparse._csr.csr_matrix'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [77]:
with open('../data/processed/onehot_representation.pkl','wb') as f:
    pickle.dump(vector, f)

In [78]:
with open('../data/processed/onehot_representation.pkl','rb') as f:
    x = pickle.load(f)
    print(x.shape)

(39774, 6782)


In [35]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

df = pd.DataFrame(X[0].T.todense(), index=vectorizer.get_feature_names(), columns=["TF-IDF"])
df.sort_values('TF-IDF',ascending=False).head(25)

/Users/askemeineche/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


TF-IDF
seasoning               0.408773
garbanzobeans           0.404069
grapetomatoes           0.377705
blackolives             0.377438
romainelettuce          0.367375
fetacheesecrumbles      0.350125
purpleonion             0.248007
pepper                  0.195801
garlic                  0.164665
10oz                    0.000000
pickledonion            0.000000
pickledokra             0.000000
pickledjalapenos        0.000000
pickledjalapenopeppers  0.000000
pickledgarlic           0.000000
pickledcarrots          0.000000
pickledvegetables       0.000000
pickledbeets            0.000000
pickapeppasauce         0.000000
picholineolives         0.000000
picholine               0.000000
picantesauce            0.000000
phyllopastry            0.000000
phyllodough             0.000000
phyllo                  0.000000

In [94]:
vector.T.shape

(6782, 39774)

In [ ]:
with_labels = np.c_[vector.T,labels]